# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # GITHUB ACTION SETUP
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # CI FOR BACKEND
    - name: Install backend
      run: npm ci
      working-directory: site/backend
    - name: Build backend
      run: npm run build --if-present
      working-directory: site/backend
    - name: Test backend
      run: npm test
      working-directory: site/backend
    # CI FOR FRONTEND
    - name: Install frontend
      run: npm ci
      working-directory: site/frontend
    - name: Build frontend
      run: npm run build --if-present
      working-directory: site/frontend
    - name: Test frontend
      run: npm test
      working-directory: site/frontend
